export class BubiOrderline {

  constructor(
    public bubiOrderLineId: string,
    public collection: string,
    public shelfmark: string,
    public counter: number,
    public fund: string,
    public price: number,
    public title: string,
    public minting: string,
    public color: string,
    public binding: string,
    public partDescription: string,
    public volume: string,
    public cover: string,
    public partTitle: string,
    public edition: string,
    public issue: string,
    public year: string,
    public part: string,
    public comment: string,
    public isFf: boolean,
    public mediaType: string,
    public standard: boolean,
    public bindingsFollow: string,
    public almaMmsId: string,
    public almaHoldingId: string,
    public almaPoLineId: string,
    public active: boolean,
    public vendorId: string,
    public alternativeBubiData: string,
    public created: Date,
    public lastChange: Date,
    public status: string
  ) {}
}
