export const LANG_DE_NAME = 'de';

export const LANG_DE_TRANS = {
  'my.settings': 'Meine Einstellungen',
  'title.fachref': 'Willkommen beim FachRef-Assistenten',
  'description.fachref.short': 'Bestandskontrolle und -steuerung bequem von einem Punkt',
  'description.fachref.medium': '',
  'title.protokoll': 'Protokoll',
  'description.protokoll.short': '',
  'description.protokoll.medium': 'Das Protokoll gibt eine Übersicht über die Nutzung und den Bestand sowohl von einzelnen Auflagen oder über mehrere Auflagen hinweg.',
  'title.eusage': 'e-Nutzung',
  'description.eusage.short': 'Die Nutzung von Zeitschriften, E-Books oder Datenbanken',
  'description.eusage.medium': 'In diesem Bereich können Nutzungsstatistiken für e-Journals, e-Books und Datenbanken abgerufen werden.',
  'title.profiles': 'Profile',
  'description.profiles.short': 'Individuelle Bestandspflege für jeden Fachbereich',
  'description.profiles.medium': 'Im Bestandspflegemodul können Profile zur Bestandspflege erstellt und verwaltet werden. Auf der Basis dieser Parametersätzen werden Listen von nutzungsbasierte Aussonderungs- und Anschaffungsvorschlägen erstellt.',
  'title.hitlists': 'Hitlisten',
  'description.hitlists.short': 'Die am stärksten vorgemerkten Titel je Fachbereich',
  'description.hitlists.medium': 'Die Vormerkhitlisten können nach Bestandsbereichen und vorgegebenen Schwellenwerten gefiltert werden. Die so gefilterten Listen können außerdem als RSS-Feeds abonniert werden.',
  'title.blacklist': 'gesperrte Titel',
  'description.blacklist.short': 'Diese Titel sind für weitere Analyse und Vormerk-Hitlisten gesperrt.',
  'description.blacklist.medium': '',
  'subject.00': 'Systemstellenanalyse',
  'subject.01': 'Allgemeines',
  'subject.04': 'Sprach- und Literaturwissenschaften',
  'subject.07': 'Germanistik',
  'subject.10': 'Anglistik',
  'subject.13': 'Romanistik',
  'subject.16': 'sonstige Philologien',
  'subject.19': 'Philosophie',
  'subject.22': 'Psychologie',
  'subject.25': 'Erziehungswissenschaften',
  'subject.28': 'Theologie',
  'subject.31': 'Autoren GW',
  'subject.34': 'Kunstwissenschaften',
  'subject.34a': 'Medienwissenschaften',
  'subject.37': 'Sportwissenschaften',
  'subject.40': 'Geschichte',
  'subject.43': 'Geowissenschaften',
  'subject.46a': 'Sozialwissenschaften',
  'subject.46b': 'Soziologie',
  'subject.46c': 'Politikwissenschaften',
  'subject.49': 'Wirtschaftswissenschaften',
  'subject.52': 'Rechtswissenscahften',
  'subject.55': 'Land- und Forstwissenschaften',
  'subject.58': 'Naturwissenschaften',
  'subject.61': 'Mathematik',
  'subject.64': 'Informatik',
  'subject.67': 'Physik',
  'subject.70': 'Chemie',
  'subject.73': 'Astronomie',
  'subject.75': 'Biologie',
  'subject.77': 'Medizin',
  'subject.77a': 'Medizin',
  'subject.79': 'Technik allgemein',
  'subject.82': 'Bauingenieurwesen',
  'subject.85': 'Maschinenbau',
  'subject.88': 'Elektrotechnik',
  'subject.91': 'Sonstige Gebiete der Technik',
  'subject.94': 'Turkistik',
  'subject.99': 'Sonderstandorte',
  'month.1': 'Januar',
  'month.2': 'Februar',
  'month.3': 'März',
  'month.4': 'April',
  'month.5': 'Mai',
  'month.6': 'Juni',
  'month.7': 'Juli',
  'month.8': 'August',
  'month.9': 'September',
  'month.10': 'Oktober',
  'month.11': 'November',
  'month.12': 'Dezember',
  'month.0': 'Jahr',
  'report.type.JR1': 'Journal Report 1',
  'report.type.JR1a': 'Journal Report 1a',
  'report.type.JR2': 'Journal Report 2',
  'report.type.JR3': 'Journal Report 3',
  'report.type.JR4': 'Journal Report 4',
  'report.type.JR5': 'Journal Report 5',
  'report.type.BR1': 'Book Report 1',
  'report.type.BR2': 'Book Report 2',
  'report.type.BR3': 'Book Report 3',
  'report.type.BR4': 'Book Report 4',
  'report.type.BR5': 'Book Report 5',
  'report.type.BR7': 'Book Report 7',
  'report.type.DB1': 'Database Report 1',
  'report.type.DB2': 'Database Report 2',
  'report.type.PR1': 'Platform Report 1',
  'report.type.M1': 'Multimedia Report 1',
  'report.type.M2': 'Multimedia Report 2',
  'report.type.TR1': 'Title Report 1',
  'report.type.TR1M': 'Title Report 1 Mobile',
  'report.type.TR2': 'Title Report 2',
  'report.type.TR3': 'Title Report 3',
  'report.type.TR3M': 'Title Report 3 Mobile',
  'status_deleted': 'aussondern',
  'status_ignored': 'ignorieren',
  'status_repository': 'umstellen',
  'back': 'Zurück',
  'proposed': 'Vorschlag',
  'deletion': 'Aussonderung',
  'repository': 'Magazin',
  'ignored': 'Sperren',
  'title.area': 'Angaben zum Bereich',
  'description.area': 'Dieser Abschnitt umfasst die notwendigen Angaben zum Fachbereich und der Medienart, die untersucht werden soll. Wird explizit eine Systemstelle angegeben, so erfolgt die  Analyse nur für diese. Soll die Analyse für die ganze Fachgruppe durchgeführt werden, bleibt das Feld leer. Ähnlich wie beim Ausleihprotokoll können Einschränkungen hinsichtlich der Standorte vorgenommen werden. Dabei gelten die gleichen.',
  'message.error.noDataFound': 'Es konnten leider keine Daten gefunden werden. Bitte einen gültigen Identifikator eingeben.',
  'confirm.delete.sushiprovider': 'Wollen Sie diesen SUSHI-Account wirklich löschen?',
  'media.ebook': 'E-Books',
  'media.journal': 'Zeitschriften',
  'aggregator.publisher': 'Herausgeber',
  'aggregator.platform': 'Plattform',
  'label.stats.aggregator': 'Gruppieren nach: ',
  'label.stats.media': 'Medium: ',
  'label.stats.identifier': 'Name (Optional): ',
  'title.stats.journal': 'E-Zeitschriftennutzung - Report',
  'title.stats.ebook': 'E-Book-Nutzung - Report',
  'table.field.identifier': 'Name',
  'table.field.year': 'Jahr',
  'table.field.month': 'Monat',
  'table.field.requests': 'Abrufe',
  'table.field.items': 'genutzte Titel',
  'usage.per.year': 'Nutzung pro Jahr',
  'usage.per.month': 'Nutzung pro Monat',
  'view.data': 'Tabelle anzeigen',
  'bubi.inbox': 'Eingang',
  'bubi.invoice': 'Rechnung bearbeiten',
  'sap': 'SAP',
  'sap.short': 'SAP Im- and Export',
  'sap.link': 'Zu den SAP-Funktionen',
  'sap.day.to.collect': 'Datum zum Abruf',
  'shibboleth': 'Shibboleth',
  'shibboleth.short': 'Einstellungen rund um Shibboleth',
  'shibboleth.link': 'Zu den Shbboleth-Profilen',
  'actions': 'Aktionen',
  'edit': 'Bearbeiten',
  'delete': 'Löschen',
  'save': 'Speichern',
  'shelfmark': 'Signatur',
  'collection': 'Standort',
  'part': 'Teil',
  'volume': 'Band',
  'color': 'Farbe',
  'minting': 'Prägung',
  'year': 'Jahr',
  'comment': 'Kommentar',
  'barcode': 'Barcode',
  'edit.success': 'Erfolgreich geändert',
  'delete.success': 'Erfolgreich gelöscht',
  'active': 'aktiv',
  'inactive': 'nicht aktiv',
  'is.active': 'Aktiv?',
  'is.ff': 'Fortsetzung?',
  'binding': 'Bindung',
  'cover': 'Cover',
  'issue': 'Heft',
  'edition': 'Ausgabe',
  'bindings.follow': 'Bindungsfolge',
  'campus': 'Campus',
  'status': 'Status',
  'fund.journal': 'Einband',
  'fund.monograph': 'Bestandserhaltung',
  'pack.success': 'Packen erfolgreich',
  'title': 'Titel',
  'D0001': 'Duisburg',
  'E0001': 'Essen',
  'alma.holding.id': 'Bestand',
  'alma.mms.id': 'MMS ID',
  'alma.po.line.id': 'Alma-Bestellposten-ID',
  'sap.collect.open': 'Alle',
  'sap.date.specific': 'Für bestimmtes Datum suchen',
  'sap.collect.open.short': 'Alle offenen Rechnungen abrufen.',
  'sap.run.result': 'Ergebnis des SAP-Laufes',
  'sap.invoice.owner': 'Besitzer',
  'sap.invoice.owner.e0001': 'Campus Essen',
  'sap.invoice.owner.d0001': 'Campus Duisburg',
  'sap.invoice.owner.e0023': 'Fachbibliothek Medizin',
  'sap.invoice.owner.ude': 'Universität Duisburg-Essen',
  'shibboleth.new.provider': 'Neuen Provider anlegen',
  'shibboleth.provider.name': 'Plattform',
  'shibboleth.provider.wayfless': 'SP-side WAYFless?',
  'invoices.collect.open': 'Abrufen',
  'upload.excel': 'Excel-Upload',
  'upload.excel.short': 'SAP-Export hochladen, um die Rechnungen zu schließen und die Belegnummer zu importieren.',
  'upload.excel.choose': 'Bitte Klicken, um Excel-Datei auszuwählen, oder Datei direkt hierher ziehen.',
  'sap.result.number.invoices': 'Anzahl Rechnungen',
  'sap.result.number.invoicelines': 'Anzahl Rechnungsposten',
  'sap.result.number.missedsapdata': 'Anzahl SAP Daten mit Fehlern',
  'sap.result.number.created.sapdata.home': ' Anzahl erzeugter SAP Daten (Inland)',
  'sap.result.number.created.sapdata.foreign ': ' Anzahl erzeugter SAP Daten (Ausland)',
  'sap.result.vendorcode': 'Vendor Code',
  'sap.result.creditor': 'Creditor',
  'sap.result.date.invoice': 'Rechnungsdatum',
  'sap.result.date.processing': 'Verarbeitungsdatum',
  'sap.result.costtype': 'Steuerschlüssel',
  'sap.result.amount': 'Summe',
  'sap.result.currency': 'Währung',
  'sap.result.invoicenumber': 'Rechnungsnummer',
  'sap.result.invoicelinenumber': 'Rechnungsposition',
  'sap.result.briefcode': 'Code',
  'sap.result.checkcode': 'Check-Wert',
  'sap.result.date.from': 'Datum von',
  'sap.result.date.to': 'Datum bis',
  'sap.result.checked': 'Geprüft?',
  'sap.title.home': 'Buchungen Inland',
  'sap.title.foreign': 'Buchungen Ausland',
  'files.heading.home': 'Buchungen Inland',
  'files.heading.foreign': 'Buchungen Ausland',
  'files.home.short': 'Alle Buchungen mit Steuerschlüsseln H8/H9 in EUR',
  'files.foreign.short': 'Alle Buchungen mit anderen Steuerschlüsseln und/oder nicht-EUR Währung',
  'files.download': 'Download SAP Datei',
  'files.entries': 'Einträge',
  'bubi.outbox': 'Ausgangsbearbeitung',
  'bubi.outbox.short': 'Ausgangsbearbeitung',
  'bubi.new.order': 'Buchbinderauftrag erfassen',
  'bubi.print.order': 'Buchbinderauftrag ausdrucken',
  'bubi.search': 'Suche',
  'bubi.search.signature': 'Signatursuche',
  'bubi.search.open.complaints': 'Offene Reklamationen',
  'bubi.search.order.number': 'Abfrage nach Auftragsnummer',
  'bubi.coredata': 'Stammdatenverwaltung',
  'bubi.coredata.change': 'Stammdaten bearbeiten und erfassen',
  'bubi.statistics': 'Statistik',
  'bubi.statistics.order': 'Auftragsstatistik',
  'bubi': 'Buchbinder',
  'bubi.short': 'Management von Buchbinderaufträgen',
  'bubi.link': 'Zu den Buchbinderaufträgen',
  'bubi.inbox.short': 'Eingangsbearbeitung',
  'bubi.search.short': 'Suche',
  'bubi.coredata.short': 'Stammdatenverwaltung',
  'bubi.coredata.upload': 'Stammdaten hochladen',
  'bubi.coredata.upload.short': 'Bereits bestehende Stammdaten können als Escel-Tabelle hochgeladen werden.',
  'bubi.statistics.short': 'Statistik',
  'bubi.order.line.new': 'Neuen Auftrag anlegen',
  'bubi.order.line.new.short': 'Bitte Signatur und Standort angeben und "anlegen" klicken.',
  'bubi.order.line.new.build': 'anlegen',
  'bubi.order.line.overview': 'Buchbinderauftrag-Übersicht',
  'bubi.order.line.overview.short': 'Hier können noch Daten für den Buchbinderauftrag angepasst werden.',
  'bubi.order.line.vendorId': 'Lieferanten-ID',
  'bubi.order.line.overview.volume.data': 'Angaben zum vorliegenden Band',
  'bubi.order.line.bindingsFollow': 'Bandfolge für den vorliegenden Band',
  'bubi.order.line.new.from.existing': 'Auftrag duplizieren',
  'bubi.order.line.new.from.existing.short': 'Einen früheren Auftrag als Grundlage für den neuen nehmen.',
  'bubi.order.line.Id': 'Auftragsnummer',
  'bubi.order.line.overview.core.data': 'Kerndaten',
  'bubi.order.line.overview.appearance': 'Daten zur Gestaltung',
  'bubi.order.line.counter': 'Zähler',
  'bubi.order.line.edit.success': 'Der Buchbibnder-Bestellposten wurde erfolgreich gespeichert.',
  'bubi.order.line.fund': 'Etat',
  'bubi.order.line.price': 'Preis',
  'bubi.order.line.new.from.collection': 'Aus Standort und Signatur',
  'bubi.order.line.new.from.barcode': 'Aus Barcode',
  'bubi.order.line.bubi': 'Buchbinder',
  'bubi.new.order.open': 'Offene Aufträge anzeigen',
  'bubi.order.pack.success': 'Alle Auftragsposten wurden zu einem Auftrag zusammengestellt.',
  'bubi.order.pack.po.id.description': 'Der neue Auftrag wurde als Bestellung in Alma angelegt. Die Bestellnummer lautet:',
  'bubi.order.pack.content': 'Folgende Alma-Bestellposten wurden in dieser Bestellung zusammengefasst:',
  'bubi.binding.none': 'Keine Angabe',
  'bubi.binding.k': 'K',
  'bubi.binding.f': 'F',
  'bubi.cover.gw': 'GW',
  'bubi.cover.gwed': 'GW ED',
  'bubi.cover.stopr.av': 'StoPr  Dbl.a.V',
  'bubi.cover.stopr.uf': 'StoPr  Dbl.u.F',
  'bubi.cover.stopr': 'StoPr',
  'bubi.cover.stmpr': 'StmPr',
  'bubi.vendor.b1115': 'Knüfken',
  'bubi.data': 'Buchbinderdaten',
  'bubi.data.overview': 'Buchbinderdaten - Übersicht',
  'bubi.data.overview.short': 'Angaben zu Bezeichnungen, Standardpreisen etc.',
  'bubi.data.new': 'Neue Buchbinderdaten erfassen',
  'bubi.data.edit': 'Buchbinderdaten bearbeiten',
  'bubi.data.edit.short': 'IDs und Standardwerte für die Buchbinder ändern.',
  'bubi.data.edit.success': 'Die Buchbinderdaten wurden erfolgreich geändert.',
  'bubi.data.delete': 'Buchbinderdaten löschen',
  'bubi.data.delete.success': 'Die Buchbinderdaten wurden erfolgreich gelöscht',
  'bubi.vendor.id': 'Lieferanten ID',
  'bubi.vendor.account': 'Lieferanten-Konto',
  'bubi.vendor.both': 'Lieferanten ID und -konto',
  'bubi.name': 'Name',
  'bubi.name.short': 'Kurzbezeichnung',
  'bubi.standard.price.monograph': 'Standardpreis Monographien',
  'bubi.standard.price.journal': 'Standardpreis Zeitschriften',
  'bubi.coredata.overview': 'Buchbinder-Stammdaten',
  'bubi.coredata.overview.short': 'Eine Überischt über alle abgelegten Stammdaten, die als Vorlage für neue Bestellposten verwendet werden.',
  'bubi.coredata.edit.success': 'Die Stammdaten wurden erfolgreich geändert.',
  'bubi.coredata.edit': 'Stammdaten bearbeiten',
  'bubi.coredata.for.item': 'Angaben zum Exemplar',
  'bubi.coredata.for.order': 'Angaben zum Auftrag',
  'bubi.coredata.for.execution': 'Angaben zur Ausführung',
  'bubi.orderline.new': 'Neuen Buchbinderauftrag anlegen',
  'bubi.orderline.new.short': 'Basierend auf den Stammdaten oder als Kopie eines existierenden einen neuen Auftragsposten anlegen.',
  'bubi.orderline.pack': 'Die Aufträge packen',
  'bubi.orderline.show.active': 'Aktiv',
  'bubi.orderline.show.waiting': 'Wartend',
  'bubi.orderline.show.sent': 'Beim Buchbinder',
  'bubi.orderline.show.all': 'Alle',
  'bubi.orderline.prepare': 'Bereitstellen',
  'bubi.orderline.show.bubi': 'Für Buchbinder',
  'bubi.orderline.overview': 'Buchbinderaufträge - Übersicht',
  'bubi.orderline.overview.short': 'Hier werden können Buchbinderaufträge gesammelt angesehen und weiterverarbeitet werden.',
  'bubi.invoice.amount.not.agree': 'Der Preis der Rechnung und des Auftrages stimmen nicht überein.'
};
