export const LANG_DE_NAME = 'de';

export const LANG_DE_TRANS = {
  'my.settings': 'Meine Einstellungen',
  'title.fachref': 'Willkommen beim FachRef-Assistenten',
  'description.fachref.short': 'Bestandskontrolle und -steuerung bequem von einem Punkt',
  'description.fachref.medium': '',
  'title.protokoll': 'Protokoll',
  'description.protokoll.short': '',
  'description.protokoll.medium': 'Das Protokoll gibt eine Übersicht über die Nutzung und den Bestand sowohl von einzelnen Auflagen oder über mehrere Auflagen hinweg.',
  'title.eusage': 'e-Nutzung',
  'description.eusage.short': 'Die Nutzung von Zeitschriften, E-Books oder Datenbanken',
  'description.eusage.medium': 'In diesem Bereich können Nutzungsstatistiken für e-Journals, e-Books und Datenbanken abgerufen werden.',
  'title.profiles': 'Profile',
  'description.profiles.short': 'Individuelle Bestandspflege für jeden Fachbereich',
  'description.profiles.medium': 'Im Bestandspflegemodul können Profile zur Bestandspflege erstellt und verwaltet werden. Auf der Basis dieser Parametersätzen werden Listen von nutzungsbasierte Aussonderungs- und Anschaffungsvorschlägen erstellt.',
  'title.hitlists': 'Hitlisten',
  'description.hitlists.short': 'Die am stärksten vorgemerkten Titel je Fachbereich',
  'description.hitlists.medium': 'Die Vormerkhitlisten können nach Bestandsbereichen und vorgegebenen Schwellenwerten gefiltert werden. Die so gefilterten Listen können außerdem als RSS-Feeds abonniert werden.',
  'title.blacklist': 'gesperrte Titel',
  'description.blacklist.short': 'Diese Titel sind für weitere Analyse und Vormerk-Hitlisten gesperrt.',
  'description.blacklist.medium': '',
  'subject.00': 'Systemstellenanalyse',
  'subject.01': 'Allgemeines',
  'subject.04': 'Sprach- und Literaturwissenschaften',
  'subject.07': 'Germanistik',
  'subject.10': 'Anglistik',
  'subject.13': 'Romanistik',
  'subject.16': 'sonstige Philologien',
  'subject.19': 'Philosophie',
  'subject.22': 'Psychologie',
  'subject.25': 'Erziehungswissenschaften',
  'subject.28': 'Theologie',
  'subject.31': 'Autoren GW',
  'subject.34': 'Kunstwissenschaften',
  'subject.34a': 'Medienwissenschaften',
  'subject.37': 'Sportwissenschaften',
  'subject.40': 'Geschichte',
  'subject.43': 'Geowissenschaften',
  'subject.46a': 'Sozialwissenschaften',
  'subject.46b': 'Soziologie',
  'subject.46c': 'Politikwissenschaften',
  'subject.49': 'Wirtschaftswissenschaften',
  'subject.52': 'Rechtswissenscahften',
  'subject.55': 'Land- und Forstwissenschaften',
  'subject.58': 'Naturwissenschaften',
  'subject.61': 'Mathematik',
  'subject.64': 'Informatik',
  'subject.67': 'Physik',
  'subject.70': 'Chemie',
  'subject.73': 'Astronomie',
  'subject.75': 'Biologie',
  'subject.77': 'Medizin',
  'subject.77a': 'Medizin',
  'subject.79': 'Technik allgemein',
  'subject.82': 'Bauingenieurwesen',
  'subject.85': 'Maschinenbau',
  'subject.88': 'Elektrotechnik',
  'subject.91': 'Sonstige Gebiete der Technik',
  'subject.94': 'Turkistik',
  'subject.99': 'Sonderstandorte',
  'month.1': 'Januar',
  'month.2': 'Februar',
  'month.3': 'März',
  'month.4': 'April',
  'month.5': 'Mai',
  'month.6': 'Juni',
  'month.7': 'Juli',
  'month.8': 'August',
  'month.9': 'September',
  'month.10': 'Oktober',
  'month.11': 'November',
  'month.12': 'Dezember',
  'month.0': 'Gesamtes Jahr',
  'report.type.JR1': 'Journal Report 1',
  'report.type.JR1a': 'Journal Report 1a',
  'report.type.JR2': 'Journal Report 2',
  'report.type.JR3': 'Journal Report 3',
  'report.type.JR4': 'Journal Report 4',
  'report.type.JR5': 'Journal Report 5',
  'report.type.BR1': 'Book Report 1',
  'report.type.BR2': 'Book Report 2',
  'report.type.BR3': 'Book Report 3',
  'report.type.BR4': 'Book Report 4',
  'report.type.BR5': 'Book Report 5',
  'report.type.BR7': 'Book Report 7',
  'report.type.DB1': 'Database Report 1',
  'report.type.DB2': 'Database Report 2',
  'report.type.PR1': 'Platform Report 1',
  'report.type.M1': 'Multimedia Report 1',
  'report.type.M2': 'Multimedia Report 2',
  'report.type.TR1': 'Title Report 1',
  'report.type.TR1M': 'Title Report 1 Mobile',
  'report.type.TR2': 'Title Report 2',
  'report.type.TR3': 'Title Report 3',
  'report.type.TR3M': 'Title Report 3 Mobile',
  'status_deleted': 'aussondern',
  'status_ignored': 'ignorieren',
  'status_repository': 'umstellen',
  'proposed': 'Vorschlag',
  'deletion': 'Aussonderung',
  'repository': 'Magazin',
  'ignored': 'Sperren',
  'title.area': 'Angaben zum Bereich',
  'description.area': 'Dieser Abschnitt umfasst die notwendigen Angaben zum Fachbereich und der Medienart, die untersucht werden soll. Wird explizit eine Systemstelle angegeben, so erfolgt die  Analyse nur für diese. Soll die Analyse für die ganze Fachgruppe durchgeführt werden, bleibt das Feld leer. Ähnlich wie beim Ausleihprotokoll können Einschränkungen hinsichtlich der Standorte vorgenommen werden. Dabei gelten die gleichen.',
  'message.error.noDataFound': 'Es konnten leider keine Daten gefunden werden. Bitte einen gültigen Identifikator eingeben.'
};
